curl -o mario.png https://www.smashbros.com/assets_v2/img/fighter/mario/main.png
curl -o donkey_kong.png https://www.smashbros.com/assets_v2/img/fighter/donkey_kong/main.png
curl -o link.png https://www.smashbros.com/assets_v2/img/fighter/link/main.png
curl -o samus.png https://www.smashbros.com/assets_v2/img/fighter/samus/main.png
curl -o dark_samus.png https://www.smashbros.com/assets_v2/img/fighter/dark_samus/main.png
curl -o yoshi.png https://www.smashbros.com/assets_v2/img/fighter/yoshi/main.png
curl -o kirby.png https://www.smashbros.com/assets_v2/img/fighter/kirby/main.png
curl -o fox.png https://www.smashbros.com/assets_v2/img/fighter/fox/main.png
curl -o pikachu.png https://www.smashbros.com/assets_v2/img/fighter/pikachu/main.png
curl -o luigi.png https://www.smashbros.com/assets_v2/img/fighter/luigi/main.png
curl -o ness.png https://www.smashbros.com/assets_v2/img/fighter/ness/main.png
curl -o captain_falcon.png https://www.smashbros.com/assets_v2/img/fighter/captain_falcon/main.png
curl -o jigglypuff.png https://www.smashbros.com/assets_v2/img/fighter/jigglypuff/main.png
curl -o peach.png https://www.smashbros.com/assets_v2/img/fighter/peach/main.png
curl -o daisy.png https://www.smashbros.com/assets_v2/img/fighter/daisy/main.png
curl -o bowser.png https://www.smashbros.com/assets_v2/img/fighter/bowser/main.png
curl -o ice_climbers.png https://www.smashbros.com/assets_v2/img/fighter/ice_climbers/main.png
curl -o sheik.png https://www.smashbros.com/assets_v2/img/fighter/sheik/main.png
curl -o zelda.png https://www.smashbros.com/assets_v2/img/fighter/zelda/main.png
curl -o dr_mario.png https://www.smashbros.com/assets_v2/img/fighter/dr_mario/main.png
curl -o pichu.png https://www.smashbros.com/assets_v2/img/fighter/pichu/main.png
curl -o falco.png https://www.smashbros.com/assets_v2/img/fighter/falco/main.png
curl -o marth.png https://www.smashbros.com/assets_v2/img/fighter/marth/main.png
curl -o lucina.png https://www.smashbros.com/assets_v2/img/fighter/lucina/main.png
curl -o young_link.png https://www.smashbros.com/assets_v2/img/fighter/young_link/main.png
curl -o ganondorf.png https://www.smashbros.com/assets_v2/img/fighter/ganondorf/main.png
curl -o mewtwo.png https://www.smashbros.com/assets_v2/img/fighter/mewtwo/main.png
curl -o roy.png https://www.smashbros.com/assets_v2/img/fighter/roy/main.png
curl -o chrom.png https://www.smashbros.com/assets_v2/img/fighter/chrom/main.png
curl -o mr_game_and_watch.png https://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/main.png
curl -o meta_knight.png https://www.smashbros.com/assets_v2/img/fighter/meta_knight/main.png
curl -o pit.png https://www.smashbros.com/assets_v2/img/fighter/pit/main.png
curl -o dark_pit.png https://www.smashbros.com/assets_v2/img/fighter/dark_pit/main.png
curl -o zero_suit_samus.png https://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/main.png
curl -o wario.png https://www.smashbros.com/assets_v2/img/fighter/wario/main.png
curl -o snake.png https://www.smashbros.com/assets_v2/img/fighter/snake/main.png
curl -o ike.png https://www.smashbros.com/assets_v2/img/fighter/ike/main.png
curl -o pokemon_trainer.png https://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/main.png
curl -o diddy_kong.png https://www.smashbros.com/assets_v2/img/fighter/diddy_kong/main.png
curl -o lucas.png https://www.smashbros.com/assets_v2/img/fighter/lucas/main.png
curl -o sonic.png https://www.smashbros.com/assets_v2/img/fighter/sonic/main.png
curl -o king_dedede.png https://www.smashbros.com/assets_v2/img/fighter/king_dedede/main.png
curl -o olimar.png https://www.smashbros.com/assets_v2/img/fighter/olimar/main.png
curl -o lucario.png https://www.smashbros.com/assets_v2/img/fighter/lucario/main.png
curl -o rob.png https://www.smashbros.com/assets_v2/img/fighter/rob/main.png
curl -o toon_link.png https://www.smashbros.com/assets_v2/img/fighter/toon_link/main.png
curl -o wolf.png https://www.smashbros.com/assets_v2/img/fighter/wolf/main.png
curl -o villager.png https://www.smashbros.com/assets_v2/img/fighter/villager/main.png
curl -o mega_man.png https://www.smashbros.com/assets_v2/img/fighter/mega_man/main.png
curl -o wii_fit_trainer.png https://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/main.png
curl -o rosalina_and_luma.png https://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/main.png
curl -o little_mac.png https://www.smashbros.com/assets_v2/img/fighter/little_mac/main.png
curl -o greninja.png https://www.smashbros.com/assets_v2/img/fighter/greninja/main.png
curl -o mii_fighter.png https://www.smashbros.com/assets_v2/img/fighter/mii_fighter/main.png
curl -o mii_fighter.png https://www.smashbros.com/assets_v2/img/fighter/mii_fighter/main.png
curl -o mii_fighter.png https://www.smashbros.com/assets_v2/img/fighter/mii_fighter/main.png
curl -o palutena.png https://www.smashbros.com/assets_v2/img/fighter/palutena/main.png
curl -o pac_man.png https://www.smashbros.com/assets_v2/img/fighter/pac_man/main.png
curl -o robin.png https://www.smashbros.com/assets_v2/img/fighter/robin/main.png
curl -o shulk.png https://www.smashbros.com/assets_v2/img/fighter/shulk/main.png
curl -o bowser_jr.png https://www.smashbros.com/assets_v2/img/fighter/bowser_jr/main.png
curl -o duck_hunt.png https://www.smashbros.com/assets_v2/img/fighter/duck_hunt/main.png
curl -o ryu.png https://www.smashbros.com/assets_v2/img/fighter/ryu/main.png
curl -o ken.png https://www.smashbros.com/assets_v2/img/fighter/ken/main.png
curl -o cloud.png https://www.smashbros.com/assets_v2/img/fighter/cloud/main.png
curl -o bayonetta.png https://www.smashbros.com/assets_v2/img/fighter/bayonetta/main.png
curl -o ridley.png https://www.smashbros.com/assets_v2/img/fighter/ridley/main.png
curl -o simon.png https://www.smashbros.com/assets_v2/img/fighter/simon/main.png
curl -o richter.png https://www.smashbros.com/assets_v2/img/fighter/richter/main.png
curl -o king_k_rool.png https://www.smashbros.com/assets_v2/img/fighter/king_k_rool/main.png
curl -o shizue.png https://www.smashbros.com/assets_v2/img/fighter/shizue/main.png
curl -o gaogaen.png https://www.smashbros.com/assets_v2/img/fighter/gaogaen/main.png
curl -o packun_flower.png https://www.smashbros.com/assets_v2/img/fighter/packun_flower/main.png
curl -o joker.png https://www.smashbros.com/assets_v2/img/fighter/joker/main.png
curl -o dq_hero.png https://www.smashbros.com/assets_v2/img/fighter/dq_hero/main.png
curl -o banjo_and_kazooie.png https://www.smashbros.com/assets_v2/img/fighter/banjo_and_kazooie/main.png
curl -o terry.png https://www.smashbros.com/assets_v2/img/fighter/terry/main.png
curl -o byleth.png https://www.smashbros.com/assets_v2/img/fighter/byleth/main.png
curl -o minmin.png https://www.smashbros.com/assets_v2/img/fighter/minmin/main.png
